title: 1st NextGenTriggers Hackathon
menu_header: hackathon
indico: https://indico.cern.ch/event/1517580/

# the jekylly-github-metadata plugin generates the site.github context
# and uses it to populate variables such as site.url and site.base_url
plugins:
  - "jekyll-github-metadata"

menu:
  - name: coroutines
    label: Coroutines in C++
  - name: eventgenerator
    label: Event Generator on GPU
    items: 
    - name: madgraph_introduction
      label: MadGraph Introduction
    - name: getting_familiar
      label: Getting Familiar
    - name: the_cudacpp_plugin
      label: The CUDACPP Plugin
    - name: profiling 
      label: Profiling
  - name: soa
    label: Structures of Arrays (SoA)
  - name: ml
    label: Fast inference in ML models
  - name: hls4ml
og    label: HLS4ML

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
